#!/usr/bin/env python

gender_lookup = {'M' : 0, 'F' : 1}

interest_lookup = {"Meh" : 1, "Low" : 2, "Sorta interested" : 3, "Really into it" : 4, "It's my life" : 5}

# Top 71 departments with number of professors > 1000. All other departments are given 0
dept_dict = {	'Linguistics': 71, 
				'Sociology': 13, 
				'Psychology': 3, 
				'Humanities': 28, 
				'Biological Sciences': 55, 
				'Government': 66, 
				'Writing': 34, 
				'Languages': 10, 
				'Religion': 32, 
				'Management': 27, 
				'Music': 16, 
				'Political Science': 14, 
				'Medicine': 68, 
				'Mathematics': 2, 
				'Social Science': 35, 
				'Classics': 52, 
				'Biology': 4, 
				'Spanish': 41, 
				'Speech': 59, 
				'Finance': 36, 
				'Business': 6, 
				'Fine Arts': 20, 
				'Not Specified': 38, 
				'Marketing': 30, 
				'Philosophy': 15, 
				'French': 58, 
				'Anthropology': 24, 
				'Information Science': 53, 
				'Statistics': 57, 
				'Computer Science': 9, 
				'Graphic Arts': 46, 
				'English As A Second Language': 70, 
				'Law': 26, 
				"Women'S Studies": 51, 
				'Electrical Engineering': 64, 
				'Theater': 29, 
				'Health Science': 23, 
				'Science': 19, 
				'Economics': 12, 
				'Journalism': 43, 
				'Theology': 45, 
				'Foreign Languages': 65, 
				'Kinesiology': 63, 
				'Literature': 49, 
				'Architecture': 48, 
				'English': 1, 
				'Business Administration': 61, 
				'Hospitality': 56, 
				'Physical Education': 44, 
				'Chemistry': 8, 'Physics': 21, 
				'Mechanical Engineering': 67, 
				'History': 5, 
				'Art History': 33, 
				'Art': 37, 
				'Nursing': 22, 
				'Communication': 7, 
				'Geology': 40, 
				'Criminal Justice': 25, 
				'Physical Ed': 42, 
				'Engineering': 17, 
				'Computer Information Systems': 69, 
				'Design': 50, 
				'Social Work': 39, 
				'Ethnic Studies': 54, 
				'Accounting': 18, 
				'International Studies': 62, 
				'Education': 11, 
				'Agriculture': 60, 
				'Film': 47, 
				'Geography': 31	}

state_div_dict = {	1 : 'Republican',
					2 : 'Neutral',
					3 : 'Democratic'}

# All states outside the US are 0
state_dict = {	'WA': 3, 
				'DE': 3, 
				'WI': 3, 
				'WV': 2, 
				'HI': 3, 
				'FL': 2, 
				'WY': 1, 
				'NH': 3, 
				'NJ': 3, 
				'NM': 3, 
				'TX': 1, 
				'LA': 1, 
				'NC': 1, 
				'ND': 1, 
				'NE': 1, 
				'TN': 1, 
				'NY': 3, 
				'PA': 3, 
				'CA': 3, 
				'NV': 2, 
				'VA': 1, 
				'CO': 2, 
				'AK': 1, 
				'AL': 1, 
				'AR': 2, 
				'VT': 3, 
				'IL': 3, 
				'GA': 1, 
				'IN': 1, 
				'IA': 3, 
				'MA': 3, 
				'AZ': 1, 
				'ID': 1, 
				'CT': 3, 
				'ME': 3, 
				'MD': 3, 
				'OK': 1, 
				'OH': 2, 
				'UT': 1, 
				'MO': 2, 
				'MN': 3, 
				'MI': 3, 
				'RI': 3, 
				'KS': 1, 
				'MT': 1, 
				'MS': 1, 
				'SC': 1, 
				'KY': 1, 
				'OR': 3, 
				'SD': 1	}

text_features_map = {'num_comments' : 23,
					'num_commas' : 24,
					'num_quotes' : 25,
					'num_semicolons' : 26,
					'num_colons' : 27,
					'num_pauses' : 28,
					'num_questions' : 29,
					'num_exclamations' : 30,
					'ADV' : 31,
					'NOUN' : 32,
					'ADP' : 33,
					'PRT' : 34,
					'DET' : 35,
					'PRON' : 36,
					'VERB' : 37,
					'NUM' : 38,
					'CONJ' : 39,
					'ADJ' : 40,
					'.' : 41,
					'X' : 42,
					'num_unq_words' : 43}

sent_features_map = {'num_positive_words' : 44,
					'num_negative_words' : 45,
					'num_positive_comments' : 46,
					'num_negative_comments' : 47}
					
